# Generated by Django 5.0.6 on 2024-06-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_creator', '0006_alter_quiz_quiz_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer_language', to='quiz_creator.language')),
                ('question_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question_language', to='quiz_creator.language')),
            ],
        ),
    ]
