# Generated by Django 5.0.6 on 2024-06-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_creator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
    ]
