# Generated by Django 5.0.6 on 2024-06-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_creator', '0002_remove_question_slug_remove_quiz_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hint',
            name='hint_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_creator.language'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_language', to='quiz_creator.language'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_language', to='quiz_creator.language'),
        ),
    ]
