# Generated by Django 5.0.6 on 2024-06-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_creator', '0003_language_alter_quizquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
