# Generated by Django 5.0.6 on 2024-06-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_creator', '0004_remove_quiz_description_delete_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quiz_creator.question'),
        ),
    ]
